-- Drop negotiation stage (no longer needed)
ALTER TABLE "projects" DROP COLUMN "stage";
DROP TYPE "ProjectStage";

-- Replace seeded areas with the sector list from im-vestor-full (production)
DELETE FROM "areas";
INSERT INTO "areas" ("id", "name") VALUES
  ('area_3d_printing', '3D Printing'),
  ('area_adtech', 'AdTech'),
  ('area_agritech', 'AgriTech'),
  ('area_ai', 'AI'),
  ('area_autonomous_vehicles', 'Autonomous Vehicles'),
  ('area_autotech', 'AutoTech'),
  ('area_biotech', 'Biotech'),
  ('area_blockchain', 'Blockchain'),
  ('area_circular_economy', 'Circular Economy'),
  ('area_climatetech', 'ClimateTech'),
  ('area_constructiontech', 'ConstructionTech'),
  ('area_cybersecurity', 'Cybersecurity'),
  ('area_developer_tools', 'Developer Tools'),
  ('area_e_commerce', 'E-commerce'),
  ('area_edtech', 'EdTech'),
  ('area_energytech', 'EnergyTech'),
  ('area_femtech', 'FemTech'),
  ('area_fintech', 'Fintech'),
  ('area_foodtech', 'FoodTech'),
  ('area_gaming', 'Gaming'),
  ('area_govtech', 'GovTech'),
  ('area_healthcare', 'Healthcare'),
  ('area_home_automation', 'Home Automation'),
  ('area_hrtech', 'HRTech'),
  ('area_insurtech', 'InsurTech'),
  ('area_iot', 'IoT'),
  ('area_legaltech', 'LegalTech'),
  ('area_logistics', 'Logistics'),
  ('area_manufacturingtech', 'ManufacturingTech'),
  ('area_marketplaces', 'Marketplaces'),
  ('area_martech', 'MarTech'),
  ('area_mediatech', 'MediaTech'),
  ('area_mobility', 'Mobility'),
  ('area_neurotech', 'NeuroTech'),
  ('area_personal_finance', 'Personal Finance'),
  ('area_proptech', 'PropTech'),
  ('area_quantum_computing', 'Quantum Computing'),
  ('area_regtech', 'RegTech'),
  ('area_retailtech', 'RetailTech'),
  ('area_robotics', 'Robotics'),
  ('area_saas', 'SaaS'),
  ('area_seniortech', 'SeniorTech'),
  ('area_social_impact_tech', 'Social Impact Tech'),
  ('area_spacetech', 'SpaceTech'),
  ('area_sportstech', 'SportsTech'),
  ('area_supply_chaintech', 'Supply ChainTech'),
  ('area_traveltech', 'TravelTech'),
  ('area_vr_ar', 'VR/AR'),
  ('area_wearable_tech', 'Wearable Tech'),
  ('area_wellnesstech', 'WellnessTech')
ON CONFLICT ("name") DO NOTHING;
